global:
  scrape_interval: 15s  # Intervalo padrão de coleta de métricas para todos os jobs

scrape_configs:
  - job_name: 'prometheus'  # Nome do job para o Prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'flask'
    static_configs:
      - targets: ['flask:5000']

  - job_name: 'mysqld_exporter'  # Nome do job para o MySQL Exporter
    static_configs:
      - targets: ['mysqld_exporter:9104']  # Definição do alvo para coletar métricas do MySQL Exporter

