# Dockerfile (Flask AppBuilder)
FROM python:3.9-slim

WORKDIR /app

COPY flask/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY flask/app.py /app/app.py


CMD ["flask", "run", "--host=0.0.0.0"]
